name_choices = {
'Adkins, Trey':'Adkins, Trey',
'Baldwin, Craig':'Baldwin, Craig',
'Bradley, John':'Bradley, John',
'Corbitt, Jeff':'Corbitt, Jeff',
'Frank, Wayne':'Frank, Wayne',
'Glascoe, Matt':'Glascoe, Matt',
'Harris, Chuck':'Harris, Chuck',
'Jablon, Joe':'Jablon, Joe',
'Johnson, Jennifer':'Johnson, Jennifer',
'Johnson, John':'Johnson, John',
'Masten, Matt':'Masten, Matt',
'Masten, Pat':'Masten, Pat',
'Masten, Thomas':'Masten, Thomas',
'Miller, Brooke':'Miller, Brooke',
'Murray, Jess':'Murray, Jess',
'Nolan, Kevin':'Nolan, Kevin',
'Patterson, Eric':'Patterson, Eric',
'Petty, Robert':'Petty, Robert',
'Pilkenton, Justin':'Pilkenton, Justin',
'Swing, Ken': 'Swing, Ken',
'Teeter, Jake':'Teeter, Jake',
'Thompson, Frank':'Thompson, Frank',
'Wagner, Terry':'Wagner, Terry',
'Williams, April':'Williams, April',
'Wortman, Darryl':'Wortman, Darryl'
}
