# Generated by Django 2.1.7 on 2019-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
            ],
        ),
    ]
