# Generated by Django 2.1.7 on 2019-03-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('weeks', '0002_auto_20190315_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playerstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(choices=[('Adkins, Trey', 'Adkins, Trey'), ('Baldwin, Craig', 'Baldwin, Craig'), ('Bradley, John', 'Bradley, John'), ('Corbitt, Jeff', 'Corbitt, Jeff'), ('Frank, Wayne', 'Frank, Wayne'), ('Glascoe, Matt', 'Glascoe, Matt'), ('Harris, Chuck', 'Harris, Chuck'), ('Jablon, Joe', 'Jablon, Joe'), ('Masten, Matt', 'Masten, Matt'), ('Masten, Pat', 'Masten, Pat'), ('Masten, Thomas', 'Masten, Thomas'), ('Miller, Brooke', 'Miller, Brooke'), ('Pilkenton, Justin', 'Pilkenton, Justin'), ('Teeter, Jake', 'Teeter, Jake'), ('Thompson, Frank', 'Thompson, Frank'), ('Wagner, Terry', 'Wagner, Terry'), ('Williams, April', 'Williams, April'), ('Wortman, Darryl', 'Wortman, Darryl'), ('Unknown', 'Unknown')], default='Unknown', max_length=30)),
                ('five_singles', models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3)),
                ('cricket_singles', models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3)),
                ('five_doubles', models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3)),
                ('cricket_doubles', models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weeks.Week')),
            ],
        ),
    ]
