# Generated by Django 2.1.7 on 2019-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstat',
            name='cricket_doubles',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='cricket_singles',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='five_doubles',
        ),
        migrations.RemoveField(
            model_name='playerstat',
            name='five_singles',
        ),
        migrations.AddField(
            model_name='playerstat',
            name='cricket_doubles_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='cricket_doubles_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='cricket_singles_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='cricket_singles_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_doubles_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_doubles_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_singles_loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_singles_win',
            field=models.IntegerField(default=0),
        ),
    ]
