# Generated by Django 2.1.5 on 2019-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstat', '0002_auto_20190319_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='player_name',
            field=models.CharField(choices=[('Adkins, Trey', 'Adkins, Trey'), ('Baldwin, Craig', 'Baldwin, Craig'), ('Bradley, John', 'Bradley, John'), ('Corbitt, Jeff', 'Corbitt, Jeff'), ('Frank, Wayne', 'Frank, Wayne'), ('Glascoe, Matt', 'Glascoe, Matt'), ('Harris, Chuck', 'Harris, Chuck'), ('Jablon, Joe', 'Jablon, Joe'), ('Johnson, Jennifer', 'Johnson, Jennifer'), ('JOhnson, John', 'JOhnson, John'), ('Masten, Matt', 'Masten, Matt'), ('Masten, Pat', 'Masten, Pat'), ('Masten, Thomas', 'Masten, Thomas'), ('Miller, Brooke', 'Miller, Brooke'), ('Murray, Jess', 'Murray, Jess'), ('Nolan, Kevin', 'Nolan, Kevin'), ('Patterson, Eric', 'Patterson, Eric'), ('Petty, Robert', 'Petty, Robert'), ('Pilkenton, Justin', 'Pilkenton, Justin'), ('Swing, Ken', 'Swing, Ken'), ('Teeter, Jake', 'Teeter, Jake'), ('Thompson, Frank', 'Thompson, Frank'), ('Wagner, Terry', 'Wagner, Terry'), ('Williams, April', 'Williams, April'), ('Wortman, Darryl', 'Wortman, Darryl'), ('Unknown', 'Unknown')], default='Unknown', max_length=30),
        ),
    ]
