# Generated by Django 2.1.7 on 2019-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerstat', '0003_auto_20190328_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstat',
            name='cricket_doubles_wldnp',
            field=models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='cricket_singles_wldnp',
            field=models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_doubles_wldnp',
            field=models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='five_singles_wldnp',
            field=models.CharField(choices=[('W', 'W'), ('L', 'L'), ('DNP', 'DNP')], default='DNP', max_length=3),
        ),
    ]
