# Generated by Django 2.1.7 on 2019-05-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerstat', '0004_auto_20190415_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
        migrations.AlterField(
            model_name='playerstat',
            name='week',    
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weeks.Week')),
        migrations.AlterField(
            model_name='playerstat',
            name='player_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to= 'players.Player'),
        ),
    ]
