# Generated by Django 2.1.7 on 2019-05-30 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playerplus', '0002_auto_20190328_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerplus',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
        migrations.AlterField(
            model_name='playerplus',
            name='week',    
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weeks.Week')),
        migrations.AlterField(
            model_name='playerplus',
            name='player_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.Player'),
        ),
    ]
