# Generated by Django 2.1.7 on 2019-03-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weeks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_one', models.CharField(max_length=2)),
                ('score_one', models.IntegerField(default=0)),
                ('team_two', models.CharField(max_length=2)),
                ('score_two', models.IntegerField(default=0)),
                ('team_three', models.CharField(max_length=2)),
                ('score_three', models.IntegerField(default=0)),
                ('team_four', models.CharField(max_length=2)),
                ('score_four', models.IntegerField(default=0)),
                ('team_five', models.CharField(max_length=2)),
                ('score_five', models.IntegerField(default=0)),
                ('team_six', models.CharField(max_length=2)),
                ('score_six', models.IntegerField(default=0)),
                ('team_seven', models.CharField(max_length=3)),
                ('score_seven', models.IntegerField(default=0)),
                ('team_eight', models.CharField(max_length=3)),
                ('score_eight', models.IntegerField(default=0)),
                ('week', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weeks.Week')),
            ],
        ),
    ]
