# Generated by Django 2.1.7 on 2019-09-10 14:49

from django.db import migrations, models
from phone_field import PhoneField


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=PhoneField(blank=True, help_text='Contact phone number'),
        ),
    ]
