# Generated by Django 2.1.7 on 2019-09-10 15:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20190910_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
